# Generated by Django 5.0.4 on 2024-05-05 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_order_quantity_alter_product_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(default='Новое', max_length=30, verbose_name='Название статуса'),
        ),
    ]
